#!/bin/bash

render() {
	echo Rendering $1 ...
	pandoc -s README.md -o index.html --template=$PANDOCTEMPLATE
}

walkdir() {
	CURRENTDIR=$*
	cd $CURRENTDIR
	
	for thing in *; do
		if [[ -f $thing ]]; then
			if [[ $thing =~ ^[README.md] ]]; then
				render $CURRENTDIR/$thing
			else
				echo FOUND NON README FILE: $thing ...			
			fi
		fi

		if [[ -d $thing ]]; then
			walkdir $thing
		fi
	done

	cd ..
}

new() {
	mkdir -p $*
	cd $*
	touch README.md
	echo "---" >> README.md
	echo "title: " >> README.md
	echo "---" >> README.md
}

main() {
	if [[ -z $PANDOCTEMPLATE ]]; then
		echo Please set the PANDOCTEMPLATE environment to the location of template.html ...
		exit 1
	fi

	OPTS=$1

	if [[ $OPTS =~ ^[new] ]];
		then new $2
	else
		walkdir $OPTS
	fi
}

main $*
