#!/bin/bash
render () {
  declare dir="$1"
  echo Building "'$dir'"
  pandoc -s -o "$dir/index.html" --quiet "$dir/README.md"
}

if [[ -n "$*" ]];then
  for i in "$@"; do
    i=${i%/README.md}
    render $i
  done
  exit
fi

declare -a pids

for i in . **/README.md; do 
  declare dir=${i/\/README.md}
  declare key=${dir/\./BASE}
  render "$dir" &
  pids["$key"]=$!
done

for pid in ${pids[*]}; do
  wait $pid
done
